#!/usr/bin/env python3
"""Spec-traceability lint and coverage cross-index (plan §4.3).

1. Every `crates/*/src/**/*.rs` module header (the leading `//!` block) must
   contain a `Spec:` citation, or the explicit exemption `Spec: none (infrastructure)`.
2. Emits a coverage table: spec section → implementing modules → covering
   vectors, to `impl/docs/coverage.md` (pass --check to only lint).

Exit status 1 on lint failure.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

IMPL = Path(__file__).resolve().parents[1]
CRATES = IMPL / "crates"
VECTORS = IMPL / "vectors"
SPEC = IMPL.parent / "v0.8"
# `§n` = Core section; a letter prefix names a v0.8 companion document: `B§n` WebRTC Media Binding,
# `G§n` Gateway Profile, `M§n` Messaging Profile, `R§n` RTP/SRTP Media Binding.
SECTION_RE = re.compile(r"([BGMR]?)§(\d+(?:\.\d+)*)")
DOCS = {
    "": ("Core", "dsip_v_0_8_decentralized_session_initiation_protocol.md", re.compile(r"^#{2,4} (\d+(?:\.\d+)*)[. ]")),
    "B": ("WebRTC Media Binding", "dsip-webrtc-media-binding-v0.8.md", re.compile(r"^#{2,4} (\d+(?:\.\d+)*)[. ]")),
    "G": ("Gateway Profile", "dsip-gateway-profile-v0.8.md", re.compile(r"^#{2,4} G§(\d+(?:\.\d+)*)")),
    "M": ("Messaging Profile", "dsip-messaging-profile-v0.8.md", re.compile(r"^#{2,4} M§(\d+(?:\.\d+)*)")),
    "R": ("RTP/SRTP Media Binding", "dsip-rtp-srtp-media-binding-v0.8-draft.md", re.compile(r"^#{2,4} R§(\d+(?:\.\d+)*)")),
}
DOC_ORDER = {p: i for i, p in enumerate(DOCS)}


def headed_sections(prefix: str) -> list[str]:
    """Every numbered section heading of a v0.8 document, as `prefix+number`."""
    _, name, heading = DOCS[prefix]
    path = SPEC / name
    if not path.exists():
        return []
    return [prefix + m.group(1) for line in path.read_text().splitlines() if (m := heading.match(line))]


def module_header(path: Path) -> str:
    lines = []
    for line in path.read_text().splitlines():
        if line.startswith("//!"):
            lines.append(line[3:])
        elif line.strip() == "" and not lines:
            continue
        else:
            break
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv
    failures = 0
    sections: dict[str, dict[str, set]] = defaultdict(lambda: {"modules": set(), "vectors": set()})
    for rs in sorted(CRATES.glob("*/src/**/*.rs")):
        header = module_header(rs)
        rel = rs.relative_to(IMPL)
        if "Spec:" not in header:
            print(f"[LINT] {rel}: module header lacks a `Spec:` line (use `Spec: none (infrastructure)` to exempt)")
            failures += 1
            continue
        text = rs.read_text()
        for prefix, num in set(SECTION_RE.findall(text)):
            sections[prefix + num]["modules"].add(str(rel))
    for vf in sorted(VECTORS.rglob("*.json")):
        if vf.name == "fixtures.json":
            continue
        v = json.loads(vf.read_text())
        for ref in v.get("spec_ref", []):
            for prefix, num in SECTION_RE.findall(ref):
                sections[prefix + num]["vectors"].add(v["vector"])
    if failures:
        print(f"\n{failures} lint failure(s)")
        return 1
    print("spec lint: all module headers carry a Spec: line")
    if check_only:
        return 0

    def split(s):
        return (s[0], s[1:]) if s[:1] in "BGMR" else ("", s)

    def key(s):
        doc, num = split(s)
        return (DOC_ORDER[doc],) + tuple(int(x) for x in num.split("."))

    def label(s):
        doc, num = split(s)
        return f"{doc}§{num}"

    out = ["# Spec coverage cross-index", "",
           "Generated by `impl/tools/spec_lint.py` from `Spec:`/`§` citations in the Rust crates and",
           "`spec_ref` fields in the vectors. A section with modules but no vectors is implemented but",
           "unpinned; a section with vectors but no modules is pinned but unimplemented.", "",
           "`§n` is a Core section; a letter names a v0.8 companion: `B§n` WebRTC Media Binding, `G§n` Gateway",
           "Profile, `M§n` Messaging Profile, `R§n` RTP/SRTP Media Binding.", "",
           "| § | implementing modules | covering vectors |", "|---|---|---|"]
    for sec in sorted(sections, key=key):
        mods = ", ".join(sorted(m.replace("crates/", "").replace("/src", "") for m in sections[sec]["modules"])) or "—"
        vecs = sections[sec]["vectors"]
        vtxt = f"{len(vecs)} vector(s): " + ", ".join(sorted(vecs)[:6]) + (" …" if len(vecs) > 6 else "") if vecs else "—"
        out.append(f"| {label(sec)} | {mods} | {vtxt} |")
    out += ["", "## Headed sections cited by neither a module nor a vector", "",
            "Numbered headings of each v0.8 document that no `Spec:` line or `spec_ref` names. A parent cited does",
            "not cover its subsections here. Informative and scope sections are expected to appear; a normative one",
            "is a candidate for the next vector.", ""]
    for prefix, (title, name, _) in DOCS.items():
        missing = [sec for sec in headed_sections(prefix) if sec not in sections]
        if missing:
            out.append(f"- **{title}** (`{name}`): " + ", ".join(label(sec) for sec in missing))
        else:
            out.append(f"- **{title}** (`{name}`): every headed section is cited")
    (IMPL / "docs" / "coverage.md").write_text("\n".join(out) + "\n")
    print(f"coverage table: {len(sections)} sections → impl/docs/coverage.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
