#!/usr/bin/env python3
"""Spec-traceability lint and coverage cross-index (plan §4.3).

1. Every `crates/*/src/**/*.rs` module header (the leading `//!` block) must
   contain a `Spec:` citation, or the explicit exemption `Spec: none (infrastructure)`.
2. Emits a coverage table: spec section → implementing modules → covering
   vectors, to `impl/docs/coverage.md` (pass --check to only lint).

Exit status 1 on lint failure.
"""
from __future__ import annotations

import json
import re
import sys
from collections import defaultdict
from pathlib import Path

IMPL = Path(__file__).resolve().parents[1]
CRATES = IMPL / "crates"
VECTORS = IMPL / "vectors"
SECTION_RE = re.compile(r"§(\d+(?:\.\d+)*)")


def module_header(path: Path) -> str:
    lines = []
    for line in path.read_text().splitlines():
        if line.startswith("//!"):
            lines.append(line[3:])
        elif line.strip() == "" and not lines:
            continue
        else:
            break
    return "\n".join(lines)


def main() -> int:
    check_only = "--check" in sys.argv
    failures = 0
    sections: dict[str, dict[str, set]] = defaultdict(lambda: {"modules": set(), "vectors": set()})
    for rs in sorted(CRATES.glob("*/src/**/*.rs")):
        header = module_header(rs)
        rel = rs.relative_to(IMPL)
        if "Spec:" not in header:
            print(f"[LINT] {rel}: module header lacks a `Spec:` line (use `Spec: none (infrastructure)` to exempt)")
            failures += 1
            continue
        text = rs.read_text()
        for sec in set(SECTION_RE.findall(text)):
            sections[sec]["modules"].add(str(rel))
    for vf in sorted(VECTORS.rglob("*.json")):
        if vf.name == "fixtures.json":
            continue
        v = json.loads(vf.read_text())
        for ref in v.get("spec_ref", []):
            for sec in SECTION_RE.findall(ref):
                sections[sec]["vectors"].add(v["vector"])
    if failures:
        print(f"\n{failures} lint failure(s)")
        return 1
    print("spec lint: all module headers carry a Spec: line")
    if check_only:
        return 0

    def key(s):
        return tuple(int(x) for x in s.split("."))

    out = ["# Spec coverage cross-index", "",
           "Generated by `impl/tools/spec_lint.py` from `Spec:`/`§` citations in the Rust crates and",
           "`spec_ref` fields in the vectors. A section with modules but no vectors is implemented but",
           "unpinned; a section with vectors but no modules is pinned but unimplemented.", "",
           "| § | implementing modules | covering vectors |", "|---|---|---|"]
    for sec in sorted(sections, key=key):
        mods = ", ".join(sorted(m.replace("crates/", "").replace("/src", "") for m in sections[sec]["modules"])) or "—"
        vecs = sections[sec]["vectors"]
        vtxt = f"{len(vecs)} vector(s): " + ", ".join(sorted(vecs)[:6]) + (" …" if len(vecs) > 6 else "") if vecs else "—"
        out.append(f"| §{sec} | {mods} | {vtxt} |")
    (IMPL / "docs" / "coverage.md").write_text("\n".join(out) + "\n")
    print(f"coverage table: {len(sections)} sections → impl/docs/coverage.md")
    return 0


if __name__ == "__main__":
    sys.exit(main())
