//! Schema freshness check.
//!
//! The schema files in the spec folder are canonical and generated by
//! `generate_schemas.py`. This script regenerates them into a scratch
//! directory and fails the build if the committed files differ, so the
//! embedded copies can never drift from the generator (plan §3, WS-2).
//! If `python3` is unavailable the check is skipped with a warning.

use std::path::{Path, PathBuf};
use std::process::Command;

fn schema_dir() -> PathBuf {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    manifest.join("../../../v0.7/dsip-schemas-v0.7-draft/dsip-schemas")
}

fn main() {
    let dir = schema_dir();
    let schemas = dir.join("schemas");
    println!("cargo:rerun-if-changed={}", schemas.display());
    println!("cargo:rerun-if-changed={}", dir.join("generate_schemas.py").display());
    for entry in std::fs::read_dir(&schemas).expect("schema dir exists") {
        println!("cargo:rerun-if-changed={}", entry.expect("entry").path().display());
    }

    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR")).join("regen");
    let status = Command::new("python3").arg(dir.join("generate_schemas.py")).arg(&out).status();
    match status {
        Ok(s) if s.success() => compare(&schemas, &out),
        _ => println!("cargo:warning=python3 unavailable; schema freshness check skipped"),
    }
}

fn compare(committed: &Path, regenerated: &Path) {
    let mut drift = vec![];
    for entry in std::fs::read_dir(regenerated).expect("regen dir") {
        let p = entry.expect("entry").path();
        let name = p.file_name().expect("name").to_owned();
        let a = std::fs::read(&p).expect("read regen");
        let b = std::fs::read(committed.join(&name)).unwrap_or_default();
        if a != b {
            drift.push(name.to_string_lossy().into_owned());
        }
    }
    if !drift.is_empty() {
        panic!(
            "schema drift: committed schemas differ from generate_schemas.py output for {:?}. \
             Regenerate with `python3 v0.7/dsip-schemas-v0.7-draft/dsip-schemas/generate_schemas.py schemas`.",
            drift
        );
    }
}
