//! The Messaging Profile schema set, embedded from the v0.8 staging folder.
//!
//! Spec: M§5, M§8 — profile message payloads and content objects have JSON Schemas (draft
//! 2020-12) generated by `v0.8/dsip-messaging-schemas-draft/generate_schemas.py`; `build.rs`
//! fails the build if the committed files drift from the generator. Impl: format assertions are
//! off, matching the Python harness and `dsip-schema`.

use std::collections::HashMap;
use std::sync::OnceLock;

use jsonschema::Validator;
use serde_json::Value;

macro_rules! schema {
    ($name:literal) => {
        ($name, include_str!(concat!("../../../../v0.8/dsip-messaging-schemas-draft/schemas/", $name, ".schema.json")))
    };
}

/// `(name, json text)` for every schema in the profile set.
pub const SCHEMAS: &[(&str, &str)] = &[
    schema!("deposit"),
    schema!("accepted"),
    schema!("sync"),
    schema!("items"),
    schema!("key-packages"),
    schema!("key-package-fetch"),
    schema!("blob-put"),
    schema!("mailbox-config"),
    schema!("content"),
    schema!("receipt"),
    schema!("activity"),
    schema!("archive-key"),
    schema!("call-event"),
    schema!("archive-record"),
    schema!("dsip-conversation"),
];

fn compiled() -> &'static HashMap<&'static str, Validator> {
    static CELL: OnceLock<HashMap<&'static str, Validator>> = OnceLock::new();
    CELL.get_or_init(|| {
        SCHEMAS
            .iter()
            .map(|(name, text)| {
                let schema: Value = serde_json::from_str(text).expect("embedded schema is JSON");
                let v = jsonschema::options()
                    .should_validate_formats(false)
                    .build(&schema)
                    .unwrap_or_else(|e| panic!("messaging schema {name} does not compile: {e}"));
                (*name, v)
            })
            .collect()
    })
}

/// Whether `instance` is valid against the named profile schema. An unknown name is invalid.
pub fn schema_ok(name: &str, instance: &Value) -> bool {
    compiled().get(name).is_some_and(|v| v.is_valid(instance))
}
